vocabulary = [

    # N5
    ("勉強", "べんきょう", "study", "N5"),
    ("学校", "がっこう", "school", "N5"),
    ("先生", "せんせい", "teacher", "N5"),
    ("学生", "がくせい", "student", "N5"),
    ("大学", "だいがく", "university", "N5"),
    ("友達", "ともだち", "friend", "N5"),
    ("家族", "かぞく", "family", "N5"),
    ("父", "ちち", "father", "N5"),
    ("母", "はは", "mother", "N5"),
    ("兄", "あに", "older brother", "N5"),
    ("姉", "あね", "older sister", "N5"),
    ("弟", "おとうと", "younger brother", "N5"),
    ("妹", "いもうと", "younger sister", "N5"),
    ("男", "おとこ", "man", "N5"),
    ("女", "おんな", "woman", "N5"),
    ("子供", "こども", "child", "N5"),
    ("人", "ひと", "person", "N5"),
    ("名前", "なまえ", "name", "N5"),
    ("先生", "せんせい", "teacher", "N5"),
    ("学生", "がくせい", "student", "N5"),
    ("会社", "かいしゃ", "company", "N5"),
    ("仕事", "しごと", "work/job", "N5"),
    ("駅", "えき", "station", "N5"),
    ("電車", "でんしゃ", "train", "N5"),
    ("車", "くるま", "car", "N5"),
    ("自転車", "じてんしゃ", "bicycle", "N5"),
    ("学校", "がっこう", "school", "N5"),
    ("病院", "びょういん", "hospital", "N5"),
    ("銀行", "ぎんこう", "bank", "N5"),
    ("店", "みせ", "shop/store", "N5"),
    ("本", "ほん", "book", "N5"),
    ("新聞", "しんぶん", "newspaper", "N5"),
    ("電話", "でんわ", "telephone", "N5"),
    ("名前", "なまえ", "name", "N5"),
    ("時間", "じかん", "time", "N5"),
    ("今日", "きょう", "today", "N5"),
    ("明日", "あした", "tomorrow", "N5"),
    ("昨日", "きのう", "yesterday", "N5"),
    ("朝", "あさ", "morning", "N5"),
    ("昼", "ひる", "noon/daytime", "N5"),
    ("夜", "よる", "night", "N5"),
    ("天気", "てんき", "weather", "N5"),
    ("雨", "あめ", "rain", "N5"),
    ("雪", "ゆき", "snow", "N5"),
    ("水", "みず", "water", "N5"),
    ("お茶", "おちゃ", "tea", "N5"),
    ("ご飯", "ごはん", "rice/meal", "N5"),
    ("食べ物", "たべもの", "food", "N5"),
    ("魚", "さかな", "fish", "N5"),
    ("肉", "にく", "meat", "N5"),
    ("野菜", "やさい", "vegetables", "N5"),
    ("果物", "くだもの", "fruit", "N5"),
    ("犬", "いぬ", "dog", "N5"),
    ("猫", "ねこ", "cat", "N5"),
    ("鳥", "とり", "bird", "N5"),
    ("花", "はな", "flower", "N5"),
    ("山", "やま", "mountain", "N5"),
    ("川", "かわ", "river", "N5"),
    ("海", "うみ", "sea", "N5"),
    ("空", "そら", "sky", "N5"),
    ("大きい", "おおきい", "big", "N5"),
    ("小さい", "ちいさい", "small", "N5"),
    ("新しい", "あたらしい", "new", "N5"),
    ("古い", "ふるい", "old", "N5"),
    ("高い", "たかい", "expensive/high", "N5"),
    ("安い", "やすい", "cheap", "N5"),
    ("長い", "ながい", "long", "N5"),
    ("短い", "みじかい", "short", "N5"),
    ("暑い", "あつい", "hot", "N5"),
    ("寒い", "さむい", "cold", "N5"),
    ("美しい", "うつくしい", "beautiful", "N5"),
    ("好き", "すき", "like/fond of", "N5"),
    ("嫌い", "きらい", "dislike/hate", "N5"),
    ("行く", "いく", "to go", "N5"),
    ("来る", "くる", "to come", "N5"),
    ("帰る", "かえる", "to return/go home", "N5"),
    ("見る", "みる", "to see/watch", "N5"),
    ("聞く", "きく", "to hear/ask", "N5"),
    ("話す", "はなす", "to speak", "N5"),
    ("読む", "よむ", "to read", "N5"),
    ("書く", "かく", "to write", "N5"),
    ("食べる", "たべる", "to eat", "N5"),
    ("飲む", "のむ", "to drink", "N5"),
    ("買う", "かう", "to buy", "N5"),
    ("使う", "つかう", "to use", "N5"),
    ("作る", "つくる", "to make", "N5"),
    ("待つ", "まつ", "to wait", "N5"),
    ("分かる", "わかる", "to understand", "N5"),
    ("ある", "ある", "to exist (inanimate)", "N5"),
    ("いる", "いる", "to exist (animate)", "N5"),

    # N4
    ("経験", "けいけん", "experience", "N4"),
    ("必要", "ひつよう", "necessary", "N4"),
    ("準備", "じゅんび", "preparation", "N4"),
    ("旅行", "りょこう", "travel/trip", "N4"),
    ("生活", "せいかつ", "daily life/living", "N4"),
    ("料理", "りょうり", "cooking/cuisine", "N4"),
    ("運転", "うんてん", "driving", "N4"),
    ("練習", "れんしゅう", "practice", "N4"),
    ("質問", "しつもん", "question", "N4"),
    ("答え", "こたえ", "answer", "N4"),
    ("問題", "もんだい", "problem/question", "N4"),
    ("説明", "せつめい", "explanation", "N4"),
    ("意味", "いみ", "meaning", "N4"),
    ("理由", "りゆう", "reason", "N4"),
    ("場所", "ばしょ", "place/location", "N4"),
    ("近く", "ちかく", "nearby", "N4"),
    ("住所", "じゅうしょ", "address", "N4"),
    ("建物", "たてもの", "building", "N4"),
    ("入口", "いりぐち", "entrance", "N4"),
    ("出口", "でぐち", "exit", "N4"),
    ("階段", "かいだん", "stairs", "N4"),
    ("部屋", "へや", "room", "N4"),
    ("台所", "だいどころ", "kitchen", "N4"),
    ("庭", "にわ", "garden", "N4"),
    ("荷物", "にもつ", "luggage/baggage", "N4"),
    ("約束", "やくそく", "promise/appointment", "N4"),
    ("予定", "よてい", "plan/schedule", "N4"),
    ("連絡", "れんらく", "contact", "N4"),
    ("電話番号", "でんわばんごう", "telephone number", "N4"),
    ("写真", "しゃしん", "photograph", "N4"),
    ("映画", "えいが", "movie", "N4"),
    ("音楽", "おんがく", "music", "N4"),
    ("歌", "うた", "song", "N4"),
    ("映画館", "えいがかん", "cinema", "N4"),
    ("公園", "こうえん", "park", "N4"),
    ("図書館", "としょかん", "library", "N4"),
    ("郵便局", "ゆうびんきょく", "post office", "N4"),
    ("交番", "こうばん", "police box", "N4"),
    ("乗る", "のる", "to ride/get on", "N4"),
    ("降りる", "おりる", "to get off", "N4"),
    ("始める", "はじめる", "to begin", "N4"),
    ("終わる", "おわる", "to finish", "N4"),
    ("続ける", "つづける", "to continue", "N4"),
    ("忘れる", "わすれる", "to forget", "N4"),
    ("覚える", "おぼえる", "to remember/learn", "N4"),
    ("考える", "かんがえる", "to think", "N4"),
    ("決める", "きめる", "to decide", "N4"),
    ("教える", "おしえる", "to teach/tell", "N4"),
    ("習う", "ならう", "to learn", "N4"),
    ("働く", "はたらく", "to work", "N4"),
    ("住む", "すむ", "to live", "N4"),
    ("借りる", "かりる", "to borrow/rent", "N4"),
    ("貸す", "かす", "to lend/rent out", "N4"),
    ("返す", "かえす", "to return something", "N4"),

    # N3
    ("経験", "けいけん", "experience", "N3"),
    ("社会", "しゃかい", "society", "N3"),
    ("世界", "せかい", "world", "N3"),
    ("政治", "せいじ", "politics", "N3"),
    ("経済", "けいざい", "economy", "N3"),
    ("文化", "ぶんか", "culture", "N3"),
    ("歴史", "れきし", "history", "N3"),
    ("環境", "かんきょう", "environment", "N3"),
    ("情報", "じょうほう", "information", "N3"),
    ("技術", "ぎじゅつ", "technology/technique", "N3"),
    ("研究", "けんきゅう", "research", "N3"),
    ("教育", "きょういく", "education", "N3"),
    ("関係", "かんけい", "relationship/connection", "N3"),
    ("原因", "げんいん", "cause", "N3"),
    ("結果", "けっか", "result", "N3"),
    ("方法", "ほうほう", "method/way", "N3"),
    ("場合", "ばあい", "case/situation", "N3"),
    ("意見", "いけん", "opinion", "N3"),
    ("目的", "もくてき", "purpose", "N3"),
    ("状況", "じょうきょう", "situation", "N3"),
    ("影響", "えいきょう", "influence/effect", "N3"),
    ("必要性", "ひつようせい", "necessity", "N3"),
    ("可能性", "かのうせい", "possibility", "N3"),
    ("安全", "あんぜん", "safety", "N3"),
    ("危険", "きけん", "danger", "N3"),
    ("注意", "ちゅうい", "caution/attention", "N3"),
    ("確認", "かくにん", "confirmation/check", "N3"),
    ("説明", "せつめい", "explanation", "N3"),
    ("利用", "りよう", "use/utilization", "N3"),
    ("増える", "ふえる", "to increase", "N3"),
    ("減る", "へる", "to decrease", "N3"),
    ("変わる", "かわる", "to change", "N3"),
    ("調べる", "しらべる", "to investigate/check", "N3"),
    ("比べる", "くらべる", "to compare", "N3"),
    ("選ぶ", "えらぶ", "to choose", "N3"),
    ("決定する", "けっていする", "to decide/determine", "N3"),
    ("必要とする", "ひつようとする", "to require", "N3"),
    ("参加する", "さんかする", "to participate", "N3"),
    ("成功する", "せいこうする", "to succeed", "N3"),
    ("失敗する", "しっぱいする", "to fail", "N3"),
    ("解決する", "かいけつする", "to solve", "N3"),
    ("紹介する", "しょうかいする", "to introduce", "N3"),
    ("説明する", "せつめいする", "to explain", "N3"),
    ("準備する", "じゅんびする", "to prepare", "N3"),
    ("研究する", "けんきゅうする", "to research", "N3"),
    ("連絡する", "れんらくする", "to contact", "N3"),
]